# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=50)),
                ('gol_dar', models.CharField(max_length=2)),
            ],
        ),
    ]
